name: CI Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Set package version and name - linux mac
      if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'mac')
      run: |
        PACKAGE_VERSION=`node -p "require('./package.json').version"`
        PACKAGE_NAME=`node -p "require('./package.json').name"`
    - name: Set package version and name - windows
      if: startsWith(matrix.os, 'windows')
      run: |
        node -p "require('./package.json').version" > tmpfilev
        set /p PACKAGE_VERSION= < tmpfilev
        del tmpfilev
        node -p "require('./package.json').name" > tmpfilen
        set /p PACKAGE_NAME= < tmpfilen
        del tmpfilen
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build
    - name: npm test
      run: npm test
      env:
        CI: true
    - name: package electron - windows
      if: startsWith(matrix.os, 'windows')
      run: npm run package:windows
    - name: package electron - linux
      if: startsWith(matrix.os, 'ubuntu')
      run: npm run package:linux
    - name: package electron - mac
      if: startsWith(matrix.os, 'mac')
      run: npm run package:mac
    - name: upload win-installer
      uses: actions/upload-artifact@master
      if: startsWith(matrix.os, 'windows')
      with:
        name: win-installer
        path: dist/installers/${process.env.PACKAGE_NAME}-${process.env.PACKAGE_VERSION}-setup.exe
    - name: upload mac-installer
      uses: actions/upload-artifact@master
      if: startsWith(matrix.os, 'mac')
      with:
        name: mac-installer
        path: dist/${process.env.PACKAGE_NAME}-${process.env.PACKAGE_VERSION}.dmg
    - name: upload linux-installer
      uses: actions/upload-artifact@master
      if: startsWith(matrix.os, 'ubuntu')
      with:
        name: linux-installer
        path: dist/installers/${process.env.PACKAGE_NAME}_${process.env.PACKAGE_VERSION}_x64.deb
