name: Add App Installers to Release

on:
  push:
    tags:
      - '*'

jobs:

  build-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name : Set package version and name
      run : |
        PACKAGE_VERSION=`node -p "require('./package.json').version"`
        PACKAGE_NAME=`node -p "require('./package.json').name"`
    - name: npm install, build, test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: npm package
      run: npm run package:mac
    - name: add app to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/${PACKAGE_NAME}-${PACKAGE_VERSION}.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name : Set package version and name
      run : |
        PACKAGE_VERSION=`node -p "require('./package.json').version"`
        PACKAGE_NAME=`node -p "require('./package.json').name"`
    - name: npm install, build, test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: npm package
      run: npm run package:linux
    - name: add app to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/installers/${PACKAGE_NAME}_${PACKAGE_VERSION}_x64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name : Set package version and name
      run : |
        set PACKAGE_VERSION=`node -p "require('./package.json').version"`
        set PACKAGE_NAME=`node -p "require('./package.json').name"`
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build
    - name: npm test
      run: npm test
      env:
        CI: true
    - name: npm package
      run: npm run package:windows
    - name: add app to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/installers/%PACKAGE_NAME%-%PACKAGE_VERSION%-setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
